services:
  testing:
    build:
      context: .
    container_name: testing-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: testing-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27000:27017"
    volumes:
      - testing-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: testing-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5555:5432"
    volumes:
      - testing-postgresql:/data/db/postgresql

volumes:
  testing-mongodb:
    driver: local
  testing-postgresql:
    driver: local
